name: My Custom Starter Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on:
      #labels: ubuntu-latest
      group: notebook

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from My Custom Starter Workflow
